import React from 'react';
import { Link } from 'react-router-dom';
import { WorkspaceShell } from '@/components/layout/WorkspaceShell';
import { useDocumentTitle } from '@/hooks/useDocumentTitle';
import { FileCode, ArrowLeft, Award, RefreshCw, CheckCircle2 } from 'lucide-react';

export const TermsRoute: React.FC = () => {
  useDocumentTitle(
    'Terms of Service & Licensing — GRIDFRAME',
    'Terms of service, open-source vector licensing terms (MIT / Open License), and distribution guidelines for GRIDFRAME.'
  );

  return (
    <WorkspaceShell>
      <div className="max-w-3xl mx-auto px-4 sm:px-6 py-12 md:py-16">
        <Link
          to="/icons"
          className="inline-flex items-center gap-1.5 text-xs font-mono text-text-tertiary hover:text-text-primary transition-colors mb-8"
        >
          <ArrowLeft className="w-3.5 h-3.5" />
          <span>BACK TO WORKSPACE</span>
        </Link>

        <div className="flex items-center gap-2 mb-3">
          <div className="w-2 h-2 rounded-full bg-accent" />
          <span className="text-[11px] font-mono tracking-widest text-text-tertiary uppercase">LEGAL & LICENSING</span>
        </div>

        <h1 className="text-2xl sm:text-3xl font-bold tracking-tight text-text-primary mb-4">
          Terms of Service & Licensing
        </h1>
        <p className="text-xs font-mono text-text-tertiary mb-8 pb-6 border-b border-border-default">
          EFFECTIVE DATE: SEPTEMBER 2026 • REVISION 2.4
        </p>

        <div className="space-y-8 text-sm text-text-secondary leading-relaxed font-sans">
          <section className="space-y-3">
            <h2 className="text-base font-semibold text-text-primary flex items-center gap-2 font-mono uppercase tracking-wider text-xs">
              <Award className="w-4 h-4 text-accent" />
              1. Vector Icon License (MIT / Open Source)
            </h2>
            <p>
              The core vector artwork catalog is derived from the canonical Iconoir library and is distributed under the permissive MIT License. You are free to use, customize, embed, and redistribute exported SVGs, React components, and icon sets in both commercial and non-commercial software products without royalty fees.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-base font-semibold text-text-primary flex items-center gap-2 font-mono uppercase tracking-wider text-xs">
              <FileCode className="w-4 h-4 text-accent" />
              2. Workstation Tooling & Code Generation
            </h2>
            <p>
              All code snippets generated by the GRIDFRAME Customizer (SVG, React JSX, Tailwind CSS classes, Lucide/Iconoir components) are provided without warranty. You maintain full ownership over custom icon configurations and exports created using the workspace.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-base font-semibold text-text-primary flex items-center gap-2 font-mono uppercase tracking-wider text-xs">
              <RefreshCw className="w-4 h-4 text-accent" />
              3. Service Availability & Modifications
            </h2>
            <p>
              GRIDFRAME is provided on an "as is" and "as available" basis. We continuously refine the catalog, geometry optimizations, and search indexing algorithms to improve accuracy and runtime performance.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-base font-semibold text-text-primary flex items-center gap-2 font-mono uppercase tracking-wider text-xs">
              <CheckCircle2 className="w-4 h-4 text-accent" />
              4. Attribution
            </h2>
            <p>
              Attribution is welcomed but not strictly required for production application builds embedding individual exported icons. We appreciate linking back to GRIDFRAME and the upstream Iconoir project where appropriate.
            </p>
          </section>
        </div>
      </div>
    </WorkspaceShell>
  );
};

export default TermsRoute;
