/**
 * GRIDFRAME ICON CATALOG (Tabler Icons v3.46.0)
 * Auto-generated by scripts/import-tabler-icons.ts - DO NOT EDIT MANUALLY
 */
import type { Icon } from '@/types/icon';
import catalogData from './catalog.json';

export const GRIDFRAME_ICONS: Icon[] = catalogData as Icon[];
export const TOTAL_ICON_COUNT = GRIDFRAME_ICONS.length;
export default GRIDFRAME_ICONS;
